plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pete.dualtimer'
    compileSdk 36

    defaultConfig {
        applicationId 'com.pete.dualtimer'
        minSdk 24
        targetSdk 36
        versionCode 3
        versionName '1.1.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
